name: "Build TOTEM with dongle"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_dongle","totem_left","totem_right"]'
      mapping: '["qwerty"]'
      tap: '["qwerty"]'
      nav: '["vi"]'
